spring:
  ai:
    vectorstore:
      redis:
        uri: redis://:password@redis-16241.c82.us-east-1-2.ec2.redns.redis-cloud.com:16241
        index: faqs
        prefix: "faq:"
        initialize-schema: true
    openai:
      temperature: 0.3
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      model: gpt-3.5-turbo
      embedding-base-url: https://api.openai.com
      #embedding-api-key: ${SPRING_AI_OPENAI_API_KEY}
      #embedding-model: text-embedding-ada-002

  main:
    allow-bean-definition-overriding: true